export default () => ({
  id: "",
  name: "Untitled simulation",
  configs: {
    projectId: "",
    title: "Untitled simulation",
    domain: {
      domainType: "FromValues",
      filename: "string",
      lenX: "",
      lenY: "",
      lenZ: "",
      gridCellsX: "",
      gridCellsY: "",
      gridCellsZ: "",
      gridDiscretization: "CartesianGrid",
    },
    permeability: {
      permeabilityUnit: "M2",
      point: {
        x: "",
        y: "",
        z: "",
      },
      averagePermeabilityAndContrast: true,
      permeabilityAverage: "10",
      permeabilityContrastLog: "5",
    },
    relativePermeabilityFunctions: {
      funcName: "Linear",
      srwRelperm: "",
      srnwRelperm: "",
      krewRelperm: "",
      krenwRelperm: "",
      wettingPhaseRelperm: "",
      nonWettingPhaseRelperm: "",
    },
    porosity: {
      value: "",
    },
    gravity: {
      customGravity: false,
      point: {
        x: "0",
        y: "0",
        z: "0",
      },
    },
    fluid: {
      name: "Immiscible",
      numberOfPhases: "TwoPhase",
      phase1Density: "",
      phase1Viscosity: "",
      phase1Compressibility: "",
      phase1HeatConductivity: "",
      phase1SpecificHeat: "",
      phase1DissolutionIntoPhase2: "0",
      phase2Density: "",
      phase2Viscosity: "",
      phase2Compressibility: "",
      phase2HeatConductivity: "",
      phase2SpecificHeat: "",
      phase2DissolutionIntoPhase1: "0",
    },
    rock: {
      name: "Sandstone",
      density: "",
      compressibility: "",
      heatConductivity: "",
      specificHeat: "",
    },
    capillarity: {
      capillaritySwitch: false,
      capillarityType: "Linear",
    },
    initialConditions: {
      initialPressure: "",
      InitialConditionType: "Temperature",
      value: "",
      initialSaturation1: "",
    },
    wells: [],
    simulation: {
      simulationTime: {
        value: "",
        simulationTimeUnit: "Days",
      },
      maximumTimesteps: "",
      reportsNumber: "",
      minTimestepSize: "",
      maxTimestepSize: "",
      outputFormat: "Ascii",
      fullyImplicitMethod: {
        maximumNonlinearIterations: "",
        nonlinearResidualToleranceEquation1: "",
        nonlinearResidualToleranceEquation2: "",
        nonlinearSolutionToleranceUnknown1: "",
        nonlinearSolutionToleranceUnknown2: "",
        maximumSizeOfCfl: "",
      },
    },
  },
});
